name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: ./.github/actions/setup-node

      - name: Run ESLint
        run: npm run lint -- --output-file eslint-report.json --format json
        continue-on-error: true

      - name: Run type checking
        run: npm run type-check

      - name: Save ESLint logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: eslint-logs
          path: test-results/eslint-report.json
          retention-days: 7

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: ./.github/actions/setup-node

      - name: Run unit tests
        run: npm run test:run

      - name: Save test logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-logs
          path: |
            test-results/
            coverage/
          retention-days: 7

  build:
    runs-on: ubuntu-latest
    needs: [lint-and-typecheck, unit-tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: ./.github/actions/setup-node

      - name: Build frontend
        run: npm run build

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: .next/
          retention-days: 7
